import { config } from 'dotenv'

// Cargar variables de entorno
config({ path: '.env' })

function setupDatabase() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL

  if (!supabaseUrl) {
    console.error('❌ Variable NEXT_PUBLIC_SUPABASE_URL no encontrada en .env')
    return
  }

  console.log('🔧 Configuración de Base de Datos para Supabase')
  console.log('📋 Ejecuta este SQL en tu Supabase Dashboard > SQL Editor:')
  console.log('')
  console.log('```sql')
  console.log('-- Tabla para reportes del mapa')
  console.log('CREATE TABLE IF NOT EXISTS map_reports (')
  console.log('  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,')
  console.log('  latitude DOUBLE PRECISION NOT NULL,')
  console.log('  longitude DOUBLE PRECISION NOT NULL,')
  console.log('  category TEXT NOT NULL,')
  console.log('  description TEXT NOT NULL,')
  console.log('  post_id UUID REFERENCES anonymous_posts(id) ON DELETE SET NULL,')
  console.log('  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()')
  console.log(');')
  console.log('')
  console.log('-- Tabla para posts anonimos del foro')
  console.log('CREATE TABLE IF NOT EXISTS anonymous_posts (')
  console.log('  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,')
  console.log('  content TEXT NOT NULL,')
  console.log('  category TEXT NOT NULL DEFAULT \'general\',')
  console.log('  image_url TEXT,')
  console.log('  map_report_id UUID REFERENCES map_reports(id) ON DELETE SET NULL,')
  console.log('  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()')
  console.log(');')
  console.log('')
  console.log('-- Tabla para comentarios anonimos')
  console.log('CREATE TABLE IF NOT EXISTS anonymous_comments (')
  console.log('  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,')
  console.log('  post_id UUID NOT NULL REFERENCES anonymous_posts(id) ON DELETE CASCADE,')
  console.log('  content TEXT NOT NULL,')
  console.log('  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()')
  console.log(');')
  console.log('')
  console.log('-- Habilitar Row Level Security')
  console.log('ALTER TABLE map_reports ENABLE ROW LEVEL SECURITY;')
  console.log('ALTER TABLE anonymous_posts ENABLE ROW LEVEL SECURITY;')
  console.log('ALTER TABLE anonymous_comments ENABLE ROW LEVEL SECURITY;')
  console.log('')
  console.log('-- Políticas de acceso público (sin autenticación requerida)')
  console.log('CREATE POLICY "Lectura publica de reportes" ON map_reports FOR SELECT USING (true);')
  console.log('CREATE POLICY "Insercion anonima de reportes" ON map_reports FOR INSERT WITH CHECK (true);')
  console.log('CREATE POLICY "Actualizacion de reportes" ON map_reports FOR UPDATE USING (true);')
  console.log('')
  console.log('CREATE POLICY "Lectura publica de posts" ON anonymous_posts FOR SELECT USING (true);')
  console.log('CREATE POLICY "Insercion anonima de posts" ON anonymous_posts FOR INSERT WITH CHECK (true);')
  console.log('CREATE POLICY "Actualizacion de posts" ON anonymous_posts FOR UPDATE USING (true);')
  console.log('')
  console.log('CREATE POLICY "Lectura publica de comentarios" ON anonymous_comments FOR SELECT USING (true);')
  console.log('CREATE POLICY "Insercion anonima de comentarios" ON anonymous_comments FOR INSERT WITH CHECK (true);')
  console.log('')
  console.log('-- Habilitar Realtime para actualizaciones en tiempo real')
  console.log('ALTER PUBLICATION supabase_realtime ADD TABLE map_reports;')
  console.log('ALTER PUBLICATION supabase_realtime ADD TABLE anonymous_posts;')
  console.log('ALTER PUBLICATION supabase_realtime ADD TABLE anonymous_comments;')
  console.log('```')
  console.log('')
  console.log('🎉 Después de ejecutar el SQL, tu aplicación debería funcionar correctamente!')
  console.log('💡 También asegúrate de que el bucket "report-images" esté creado y sea público en Storage.')
}

setupDatabase()