export type SecurityLevel = "seguro" | "precaucion" | "riesgo"

export interface PostalCodeEntry {
  cp: string
  level: SecurityLevel
  colonias: string
}

export const SECURITY_COLORS: Record<SecurityLevel, string> = {
  seguro: "#22c55e",     // green-500
  precaucion: "#f97316", // orange-500
  riesgo: "#eab308",     // yellow-500
}

export const SECURITY_LABELS: Record<SecurityLevel, string> = {
  seguro: "Seguro",
  precaucion: "Se recomienda evitar ciertas calles",
  riesgo: "No se recomienda transitar de noche",
}

// Raw data parsed from the provided table
// "Seguro" -> seguro | "Se recomienda evitar ciertas calles" -> precaucion | "No se recomienda transitar de noche" -> riesgo
export const POSTAL_CODES: PostalCodeEntry[] = [
  { cp: "34000", level: "seguro",     colonias: "Centro Histórico / Lomas del Parque / Los Remedios" },
  { cp: "34005", level: "seguro",     colonias: "Centro Histórico / Lomas del Parque / Los Remedios" },
  { cp: "34008", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34009", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34010", level: "riesgo",     colonias: "Morga / Emiliano Zapata / Tierra y Libertad" },
  { cp: "34014", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34015", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34016", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34017", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34018", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34019", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34020", level: "riesgo",     colonias: "Morga / Emiliano Zapata / Tierra y Libertad" },
  { cp: "34024", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34027", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34028", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34029", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34030", level: "riesgo",     colonias: "Morga / Emiliano Zapata / Tierra y Libertad" },
  { cp: "34037", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34038", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34039", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34040", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34043", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34045", level: "seguro",     colonias: "Centro Histórico / Lomas del Parque / Los Remedios" },
  { cp: "34046", level: "seguro",     colonias: "Centro Histórico / Lomas del Parque / Los Remedios" },
  { cp: "34047", level: "seguro",     colonias: "Centro Histórico / Lomas del Parque / Los Remedios" },
  { cp: "34048", level: "seguro",     colonias: "Centro Histórico / Lomas del Parque / Los Remedios" },
  { cp: "34049", level: "seguro",     colonias: "Centro Histórico / Lomas del Parque / Los Remedios" },
  { cp: "34050", level: "riesgo",     colonias: "Morga / Emiliano Zapata / Tierra y Libertad" },
  { cp: "34058", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34060", level: "riesgo",     colonias: "Morga / Emiliano Zapata / Tierra y Libertad" },
  { cp: "34069", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34070", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34074", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34075", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34076", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34077", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34078", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34079", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34080", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34090", level: "precaucion", colonias: "Maderera / Esparza / Barrios antiguos" },
  { cp: "34100", level: "seguro",     colonias: "Nueva Vizcaya / Fracc. Guadalupe" },
  { cp: "34103", level: "seguro",     colonias: "Nueva Vizcaya / Fracc. Guadalupe" },
  { cp: "34104", level: "seguro",     colonias: "Nueva Vizcaya / Fracc. Guadalupe" },
  { cp: "34105", level: "seguro",     colonias: "Nueva Vizcaya / Fracc. Guadalupe" },
  { cp: "34106", level: "seguro",     colonias: "Nueva Vizcaya / Fracc. Guadalupe" },
  { cp: "34107", level: "seguro",     colonias: "Nueva Vizcaya / Fracc. Guadalupe" },
  { cp: "34108", level: "seguro",     colonias: "Nueva Vizcaya / Fracc. Guadalupe" },
  { cp: "34109", level: "seguro",     colonias: "Nueva Vizcaya / Fracc. Guadalupe" },
  { cp: "34110", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34113", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34116", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34118", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34119", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34120", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34123", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34124", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34125", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34126", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34127", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34128", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34129", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34130", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34135", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34136", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34137", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34138", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34139", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34140", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34144", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34145", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34146", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34147", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34150", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34156", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34157", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34158", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34159", level: "precaucion", colonias: "Fidel Velázquez / Ciudad Industrial / 20 de Nov" },
  { cp: "34160", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34162", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34163", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34164", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34165", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34166", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34167", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34168", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34169", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34170", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34175", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34176", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34179", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34180", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34185", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34186", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34187", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34188", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34189", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34190", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34193", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34194", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34195", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34196", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34197", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34198", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34199", level: "riesgo",     colonias: "Villas del Guadiana (Zonas Periféricas)" },
  { cp: "34200", level: "seguro",     colonias: "Fracc. El Edén / Real del Mezquital" },
  { cp: "34204", level: "seguro",     colonias: "Fracc. El Edén / Real del Mezquital" },
  { cp: "34205", level: "seguro",     colonias: "Fracc. El Edén / Real del Mezquital" },
  { cp: "34206", level: "seguro",     colonias: "Fracc. El Edén / Real del Mezquital" },
  { cp: "34207", level: "seguro",     colonias: "Fracc. El Edén / Real del Mezquital" },
  { cp: "34208", level: "seguro",     colonias: "Fracc. El Edén / Real del Mezquital" },
  { cp: "34209", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34210", level: "seguro",     colonias: "Fracc. El Edén / Real del Mezquital" },
  { cp: "34214", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34215", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34216", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34217", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34218", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34219", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34220", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34224", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34225", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34226", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34227", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34228", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34229", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34230", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34233", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34234", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34235", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34236", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34237", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34238", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34239", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34240", level: "precaucion", colonias: "Huizache / Jalisco / Valle Verde" },
  { cp: "34250", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34260", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34269", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34270", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34277", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34278", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34279", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34280", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34284", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34285", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34286", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34287", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34289", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34290", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34298", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
  { cp: "34299", level: "riesgo",     colonias: "Asentamientos Humanos / División del Norte / La Virgen" },
]

// Build a quick lookup map: cp -> entry
export const CP_LOOKUP = new Map(POSTAL_CODES.map((e) => [e.cp, e]))
